Add how to re-enable SecurityAutoConfiguration doc
spring-cloud-stream-app-starters/http pull request #19
Opened 2018-08-08 13:10 UTC by tzolov

Resolves #18

2018-08-08 13:37 UTC, artembilan requested changes

2018-08-08 13:37 UTC, artembilan commented on spring-cloud-starter-stream-source-http/README.adoc
> +Also you must override the default `spring.autoconfigure.exclude` property by setting it to void (e.g. `--spring.autoconfigure.exclude=`)
The real problem that we always have to specify this property even if we don't enable security.
That's indeed a bit awkward, but we don't have choice so far: to make this app working at all we always need to use this property.

We need to rephrase it somehow to reflect reality, maybe even point to the issue we are going to fix on the matter...

2018-08-21 16:37 UTC, sabbyanandan commented
@tzolov: Let's pair on this when you return.

2018-08-30 16:13 UTC, artembilan commented
Rejected in favor of #23

2018-08-30 16:13 UTC, closed without merging