Change media type to String
spring-cloud-stream-app-starters/http pull request #26
Opened 2018-11-15 23:41 UTC by garyrussell

@sobychacko @olegz This should work but the Binder channel interceptor is changing it back to a `MimeType`. So I am confused that it's only a problem with the HTTP source.

We need the interceptor to populate it as String.

2018-11-15 23:53 UTC, artembilan requested changes

2018-11-15 23:53 UTC, artembilan commented on spring-cloud-starter-stream-source-http/src/main/java/org/springframework/cloud/stream/app/http/source/HttpSourceConfiguration.java
> +						+ "headers['" + MessageHeaders.CONTENT_TYPE + "'].toString()", true))
You can simply this expression with the null-safe navigator operator:
```
headers['" + MessageHeaders.CONTENT_TYPE + "']?.toString()
```

2018-11-15 23:59 UTC, garyrussell commented
@olegz @sobychacko @artembilan Another (perhaps simpler) alternative would be to simply copy the 2.2 spring-kafka `DefaultKafkaHeaderMapper` into SCSt and wire it into the consumer endpoint.

https://github.com/spring-projects/spring-kafka/pull/735/files#diff-783145f0f1655212681eff59eec36a7c

2018-11-16 19:40 UTC, garyrussell commented
Superseded by 8591cc59a541e9ed3240134e9bfb29dab694af3a

2018-11-16 19:40 UTC, closed without merging